module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Rocky',
    'Snowy',
    'Ocean',
    'Quiet',
    'Fossilized',
    'Ruined',
    'Lovely',
    'Redwood',
    'Silent',
    'Sandy',
    'Deserted',
    'Frozen',
    'Delicate',
    'Old-Timey',
    'Comfy',
    'Mile High',
    'Swampy',
    'Green',
    'Broken',
    'Haunted'
]

module.exports.places = [
    'Canyon',
    'Flats',
    'Pond',
    'Ground Camp',
    'Horse Camp',
    'Camp',
    'Bay',
    'Village',
    'Spring',
    'Cliffs',
    'Hunting Camp',
    'Creek',
    'Valley',
    'Mountains',
    'Dig Site',
    'Backcountry',
    'Sands',
    'Bayshore',
    'Ghost Town',
    'Flatlands',
    'Fields'
]